name: build

on:
#  push:
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.3

    - run: bundle install

    - run: bundle exec rake build

    - uses: actions/upload-artifact@v4
      with:
        name: pkg-ruby
        path: pkg/*.gem

    - run: rm pkg/*.gem

    - run: bundle exec rake --tasks

    - run: bundle exec rake gem:native:$(ruby -e "puts RUBY_PLATFORM")

    - uses: actions/upload-artifact@v4
      with:
        name: pkg-x86_64-linux
        path: pkg/*.gem

  alpine:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
    - name: Install packages
      run: |
        apk --no-cache --upgrade add build-base cmake git bash ruby-dev

    - uses: actions/checkout@v4

    - run: gem install bundler

    - run: bundle install

    - run: bundle exec rake --tasks

    - run: bundle exec rake gem:native:$(ruby -e "puts RUBY_PLATFORM")

    - uses: actions/upload-artifact@v4
      with:
        name: pkg-x86_64-linux-musl
        path: pkg/*.gem
