name: build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.3

    - name: Install bundle
      run: bundle install

    - name: Build gem
      run: bundle exec rake build

    - uses: actions/upload-artifact@v4
      with:
        name: pkg-ruby
        path: pkg/*.gem

    - name: Build gem with native extension
      run: |
        rm pkg/*.gem
        bundle exec rake gem:native:$(ruby -e "puts RUBY_PLATFORM")

  alpine:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
    - name: Install packages
      run: |
        apk --no-cache --upgrade add build-base cmake git bash ruby-dev
        git config --global --add safe.directory /__w/test-gem/test-gem

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install bundle
      run: |
        gem install bundler
        bundle install

    - name: Build gem with native extension
      run: bundle exec rake gem:native:$(ruby -e "puts RUBY_PLATFORM")
