name: release

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Next release version. Possible values: x.y.z, major, minor, patch or pre|rc|etc
        required: true
        default: 'patch'
#  push:
#    tags: [ v* ]

jobs:
  bump:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          gem install gem-release
          gem bump --version ${{ github.event.inputs.next_version }} --tag --push

  ubuntu:
    runs-on: ubuntu-latest
    needs: bump

    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.3

    - run: bundle install

    - run: bundle exec rake build

    - uses: actions/upload-artifact@v2
      with:
        name: pkg-ruby
        path: pkg/*.gem

    - run: rm pkg/*.gem

    - run: bundle exec rake --tasks

    - run: bundle exec rake gem:native:$(ruby -e "puts RUBY_PLATFORM")

    - uses: actions/upload-artifact@v2
      with:
        name: pkg-x86_64-linux
        path: pkg/*.gem

  alpine:
    runs-on: ubuntu-latest
    needs: bump
    container:
      image: alpine:latest

    steps:
    - name: Install packages
      run: |
        apk --no-cache --upgrade add build-base cmake git bash ruby-dev

    - uses: actions/checkout@v3

    - run: gem install bundler

    - run: bundle install

    - run: bundle exec rake --tasks

    - run: bundle exec rake gem:native:$(ruby -e "puts RUBY_PLATFORM")

    - uses: actions/upload-artifact@v2
      with:
        name: pkg-x86_64-linux-musl
        path: pkg/*.gem

  publish:
    runs-on: ubuntu-latest
    needs: [ubuntu, alpine]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: pkg-ruby
          path: pkg

      - uses: actions/download-artifact@v2
        with:
          name: pkg-x86_64-linux
          path: pkg

      - uses: actions/download-artifact@v2
        with:
          name: pkg-x86_64-linux-musl
          path: pkg

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - run: ls -l pkg/

      - name: Publish to rubygems.org
        env:
          RUBYGEMS_API_KEY: ${{ secrets.MAXIRMX_RUBYGEM_API_KEY }}
        run: |
          mkdir -p ~/.gem
          cat > ~/.gem/credentials << EOF
          ---
          :rubygems_api_key: ${RUBYGEMS_API_KEY}
          EOF
          chmod 0600 ~/.gem/credentials
          gem signin
          for gem in pkg/*.gem; do gem push $gem -V; done
