name: release

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Next release version. Possible values: x.y.z, major, minor, patch or pre|rc|etc
        required: true
        default: 'patch'
#  push:
#    tags: [ v* ]
permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          gem install gem-release
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          gem bump --version ${{ github.event.inputs.next_version }} --tag --push

  ubuntu:
    runs-on: ubuntu-latest
    needs: bump

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.3

    - name: Install bundle
      run: bundle install

    - name: Build gem
      run: bundle exec rake build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pkg-ruby
        path: pkg/*.gem

    - name: Build gem with native extension
      run: |
        rm pkg/*.gem
        bundle exec rake gem:native:$(ruby -e "puts RUBY_PLATFORM")

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pkg-x86_64-linux
        path: pkg/*.gem

  alpine:
    runs-on: ubuntu-latest
    needs: bump
    container:
      image: alpine:latest

    steps:
      - name: Install packages
        run: |
          apk --no-cache --upgrade add build-base cmake git bash ruby-dev
          git config --global --add safe.directory /__w/test-gem/test-gem

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bundle
        run: |
          gem install bundler
          bundle install

      - name: Build gem with native extension
        run: bundle exec rake gem:native:$(ruby -e "puts RUBY_PLATFORM")

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pkg-x86_64-linux-musl
          path: pkg/*.gem

  publish:
    runs-on: ubuntu-latest
    needs: [ubuntu, alpine]
    steps:
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: pkg-*
          path: pkg

      - run: ls -l pkg/

      - name: Publish to rubygems.org
        env:
          RUBYGEMS_API_KEY: ${{ secrets.MAXIRMX_RUBYGEM_API_KEY }}
        run: |
          mkdir -p ~/.gem
          cat > ~/.gem/credentials << EOF
          ---
          :rubygems_api_key: ${RUBYGEMS_API_KEY}
          EOF
          chmod 0600 ~/.gem/credentials
          gem signin
          for gem in pkg/*.gem; do gem push $gem -V; done
